[isotools] Jessie's debian-cd (:jessie:)
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/internal/isotools-jessie@40194 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/debian-cd/tools/boot/wheezy/boot-hppa b/debian-cd/tools/boot/wheezy/boot-hppa
--- a/debian-cd/tools/boot/wheezy/boot-hppa
+++ b/debian-cd/tools/boot/wheezy/boot-hppa
@@ -29,10 +29,19 @@ if [ $N != 1 -a $N != 1_NONUS ]; then
 	exit 0
 fi
 
-PALODEB="$($BASEDIR/tools/apt-selection cache show palo | \
-	sed -n 's/^Filename: \(.*_hppa.deb\)$/\1/p')"
-ar p "${MIRROR}/${PALODEB}" data.tar.gz | tar xz ./usr/share/palo/iplboot
+PALODEB=$(find_pkg_file palo)
+if [ -z "$PALODEB" ] ; then 
+    echo "ERROR:  the palo package is required." >&2
+    exit 1
+fi
+(dpkg --fsys-tarfile "$MIRROR/$PALODEB" | \
+    tar xf - -C . ./usr/share/palo/iplboot)
 mv usr/share/palo/iplboot $CDROOT/install/iplboot
+
+if [ -n "$ARCHIVE_EXTRACTED_SOURCES" ]; then
+    echo $PALODEB >> $CDDIR/../$N.pkgs_extracted
+    find_pkg_file palo source >> $CDDIR/../$N.pkgs_extracted
+fi
 
 if [ ! "$DI_WWW_HOME" ];then
         if [ ! "$DI_DIR" ];then
diff --git a/debian-cd/tools/boot/wheezy/boot-mipsel b/debian-cd/tools/boot/wheezy/boot-mipsel
--- a/debian-cd/tools/boot/wheezy/boot-mipsel
+++ b/debian-cd/tools/boot/wheezy/boot-mipsel
@@ -44,11 +44,20 @@ if [ $NN != 1 ]; then
 	exit 0
 fi
 
-DELODEB="$($BASEDIR/tools/apt-selection cache show delo | \
-	sed -n 's/^Filename: \(.*_mipsel.deb\)$/\1/p')"
-ar p "${MIRROR}/${DELODEB}" data.tar.gz | tar xz ./boot/delo.2nd
+DELODEB=$(find_pkg_file delo)
+if [ -z "$DELODEB" ] ; then 
+    echo "ERROR:  the delo package is required." >&2
+    exit 1
+fi
+(dpkg --fsys-tarfile "$MIRROR/$DELODEB" | \
+    tar xf - -C . ./boot/delo.2nd)
 mkdir -p $CDROOT/boot
 mv boot/delo.2nd $CDROOT/boot/delo.2nd
+
+if [ -n "$ARCHIVE_EXTRACTED_SOURCES" ]; then
+    echo $DELODEB >> $CDDIR/../$N.pkgs_extracted
+    find_pkg_file delo source >> $CDDIR/../$N.pkgs_extracted
+fi
 
 install -m 644 -D $BASEDIR/data/wheezy/delo.conf "$CDROOT"/etc/delo.conf
 
diff --git a/debian-cd/tools/boot/wheezy/boot-x86 b/debian-cd/tools/boot/wheezy/boot-x86
--- a/debian-cd/tools/boot/wheezy/boot-x86
+++ b/debian-cd/tools/boot/wheezy/boot-x86
@@ -35,6 +35,16 @@ if [ ! "$DI_DIST" ]; then
 	DI_DIST="$DI_CODENAME"
 fi
 
+case "$MKISOFS" in
+    *xorriso*)
+        XORRISO_VER=$(xorriso_version)
+        ;;
+    *)
+	echo "ERROR: debian-cd now depends on xorriso for making x86 bootable CDs."
+	exit 1;
+	;;
+esac
+
 cd $CDDIR/..
 
 # This script is called with $1 (now $N) as the CD to make bootable.
@@ -50,16 +60,6 @@ if [ $NN != 1 ] ; then exit 0; fi
 
 INSTALLDIR_i386="install.386"
 INSTALLDIR_amd64="install.amd"
-
-case "$MKISOFS" in
-    *xorriso*)
-        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-isohybrid-mbr syslinux/usr/lib/syslinux/isohdpfx.bin"
-        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-partition_offset 16"
-# uncoment to add a small FAT partition on the media
-#        /sbin/mkfs.msdos -n Bla -C test.fat 8192
-#      add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-append_partition 2 0x01 test.fat"
-       ;;
-esac
 
 if [ "$ARCH" = i386 ]; then
 	INSTALLDIR="$INSTALLDIR_i386"
@@ -181,7 +181,9 @@ echo "  Using ISOLINUX boot-disks image on CD$N"
 mkdir -p $CDDIR/$INSTALLDIR
 cp -lf cdrom/vmlinuz $CDDIR/$INSTALLDIR/
 cp -lf cdrom/initrd.gz $CDDIR/$INSTALLDIR/
-echo "\\tools\\loadlin.exe vmlinuz initrd=initrd.gz" | todos > $CDDIR/$INSTALLDIR/install.bat
+if [ -e $CDDIR/tools/loadlin.exe ]; then
+	echo "\\tools\\loadlin.exe vmlinuz initrd=initrd.gz" | todos > $CDDIR/$INSTALLDIR/install.bat
+fi
 
 mkdir -p $CDDIR/../syslinux
 SYSLINUXDEB=$(find_pkg_file syslinux)
@@ -192,17 +194,12 @@ fi
 (dpkg --fsys-tarfile "$MIRROR/$SYSLINUXDEB" | \
 	tar xf - -C $CDDIR/../syslinux ./usr/lib)
 
-echo $SYSLINUXDEB >> $CDDIR/../$N.pkgs_extracted
-find_pkg_file syslinux source >> $CDDIR/../$N.pkgs_extracted
+if [ -n "$ARCHIVE_EXTRACTED_SOURCES" ]; then
+	echo $SYSLINUXDEB >> $CDDIR/../$N.pkgs_extracted
+	find_pkg_file syslinux source >> $CDDIR/../$N.pkgs_extracted
+fi
 
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-b isolinux/isolinux.bin"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-c isolinux/boot.cat"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-no-emul-boot"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-boot-load-size 4"
-add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-boot-info-table"	
-add_mkisofs_opt $CDDIR/../$N.mkisofs_dirs "boot$N"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-isohybrid-mbr syslinux/usr/lib/syslinux/isohdpfx.bin"
 
 # In case of a multi-arch CD the script will be called two times. The
 # first time the isolinux dir gets set up for single arch; if it is
@@ -219,6 +216,12 @@ fi
 mkdir -p boot$N/isolinux
 # Isolinux setup including config and help files comes from d-i.
 cat cdrom/debian-cd_info.tar.gz | (cd boot$N/isolinux/; tar zx)
+
+# If we don't have grub stuff from d-i, tell xorriso to add a
+# partition offset for the isohybrid code
+if [ ! -d boot$N/isolinux/grub ] ; then
+    add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-partition_offset 16"
+fi
 
 di_syslinux_ver="$(di_syslinux_version)"
 case "$di_syslinux_ver" in
@@ -249,15 +252,16 @@ if [ -e boot$N/isolinux/f3.txt.withgtk ]; then
 	if [ -e boot$N/isolinux/isolinux.cfg.withgtk ]; then
 		mv boot$N/isolinux/isolinux.cfg.withgtk boot$N/isolinux/isolinux.cfg
 	fi
-	echo "\\tools\\loadlin.exe \\$INSTALLDIR\\vmlinuz initrd=initrd.gz vga=788" | todos > $CDDIR/$INSTALLDIR/gtk/install.bat
-
+	if [ -e $CDDIR/tools/loadlin.exe ]; then
+		echo "\\tools\\loadlin.exe \\$INSTALLDIR\\vmlinuz initrd=initrd.gz vga=788" | todos > $CDDIR/$INSTALLDIR/gtk/install.bat
+	fi
 fi
 rm -f boot$N/isolinux/isolinux.cfg.with*
 
 if variant_enabled "xen" ; then
 	extra_image xen/vmlinuz         "../vmlinuz   ../gtk/vmlinuz"
 	extra_image xen/initrd.gz       "../initrd.gz ../gtk/initrd.gz"
-	extra_image xen/xm-debian.cfg
+	extra_image xen/debian.cfg || extra_image xen/xm-debian.cfg
 fi
 
 # Modify win32-loader.ini for the "current" arch
@@ -270,34 +274,38 @@ fi
 
 cp -f $CDDIR/../syslinux/usr/lib/syslinux/isolinux.bin boot$N/isolinux/
 cp -f $CDDIR/../syslinux/usr/lib/syslinux/vesamenu.c32 boot$N/isolinux/
+if [ -e $CDDIR/../syslinux/usr/lib/syslinux/ldlinux.c32 ]; then
+	cp -f $CDDIR/../syslinux/usr/lib/syslinux/ldlinux.c32 boot$N/isolinux/
+	cp -f $CDDIR/../syslinux/usr/lib/syslinux/libcom32.c32 boot$N/isolinux/
+	cp -f $CDDIR/../syslinux/usr/lib/syslinux/libutil.c32 boot$N/isolinux/
+fi
 
 if [ -z "$MULTIARCH" ]; then
 	# Set up isolinux dir for only the current arch
-	sed -i "s|%install%|$INSTALLDIR|" \
-		boot$N/isolinux/*.cfg boot$N/isolinux/desktop/*.cfg
+	grep -lr '%install%' boot$N/isolinux/* | xargs -r sed -i "s|%install%|$INSTALLDIR|"
     
 	# Remove the amd*.cfg files to avoid them being loaded on a
 	# disc that does not have both amd64 and i386 dirs.
-	rm -f boot$N/isolinux/amd*.cfg boot$N/isolinux/desktop/amd*.cfg
+	find boot$N/isolinux/ -name "amd*.cfg" -delete
 else
 	# Set up isolinux dir for multi-arch
-	sed -i "s|%install%|$INSTALLDIR_i386|
-			s|%install-amd%|$INSTALLDIR_amd64|" \
-			    boot$N/isolinux/*.cfg boot$N/isolinux/desktop/*.cfg
+	grep -lr '%install[-amd]*%' boot$N/isolinux/* | xargs -r sed -i -e "s|%install%|$INSTALLDIR_i386|" -e "s|%install-amd%|$INSTALLDIR_amd64|"
 
 	for file in boot$N/isolinux/f3.txt* boot$N/isolinux/f4.txt*; do
 		sed -i "4 s/^$/(note: i386 is default; prepend 'amd64-' to use an amd64 kernel instead)/" $file
 	done
 
-	# Modify win32-loader.ini to also cover the "other" arch
-	if [ "$ARCH" = i386 ]; then
-		sed -i -e "/^arch=/d
-				   /^i386\//p; s/^i386/amd64/; s/=$INSTALLDIR_i386/=$INSTALLDIR_amd64/g" \
-				       boot$N/win32-loader.ini
-	else
-		sed -i -e "/^arch=/d
-				   /^amd64\//p; s/^amd64/i386/; s/=$INSTALLDIR_amd64/=$INSTALLDIR_i386/g" \
-				       boot$N/win32-loader.ini
+	if [ -e boot$N/win32-loader.ini ]; then
+		# Modify win32-loader.ini to also cover the "other" arch
+		if [ "$ARCH" = i386 ]; then
+			sed -i -e "/^arch=/d
+					   /^i386\//p; s/^i386/amd64/; s/=$INSTALLDIR_i386/=$INSTALLDIR_amd64/g" \
+					       boot$N/win32-loader.ini
+		else
+			sed -i -e "/^arch=/d
+					   /^amd64\//p; s/^amd64/i386/; s/=$INSTALLDIR_amd64/=$INSTALLDIR_i386/g" \
+					       boot$N/win32-loader.ini
+		fi
 	fi
 
 	# Apply workaround for #505243
@@ -362,11 +370,24 @@ if [ -f boot$N/setup.exe ]; then
 	todos > $CDDIR/autorun.inf <<EOF
 [autorun]
 open=setup.exe
+icon=setup.exe,0
+label=Install Debian GNU/Linux
+
+[Content]
+MusicFiles=false
+PictureFiles=false
+VideoFiles=false
 EOF
 elif [ -f $CDDIR/README.html ]; then
 	todos > $CDDIR/autorun.inf <<EOF
 [autorun]
 open=autorun.bat
+label=Install Debian GNU/Linux
+
+[Content]
+MusicFiles=false
+PictureFiles=false
+VideoFiles=false
 EOF
 	todos > $CDDIR/autorun.bat <<EOF
 @echo Starting "README.html"...
@@ -377,4 +398,80 @@ fi
 
 rm -rf cdrom floppy
 
+# Common mkisofs options when creating CDs
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-J -joliet-long"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-cache-inodes"
+
+# Add the normal options to make an ElTorito bootable CD/DVD
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-b isolinux/isolinux.bin"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-c isolinux/boot.cat"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-no-emul-boot"
+bls=4 # Specify 4 for BIOS boot, don't calculate it
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-boot-load-size $bls"
+add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-boot-info-table"	
+
+# We explicitly put the boot bits in boot$N (as opposed to CD$N) and
+# list it first on the eventual mkisofs command line. That means
+# they'll be placed nearer the front of the eventual image; some older
+# BIOSes apparently have a limitation on what they'll boot here.
+add_mkisofs_opt $CDDIR/../$N.mkisofs_dirs "boot$N"
+
+if [ -d boot$N/isolinux/grub ] ; then
+    echo "  Adding EFI boot code for $ARCH on CD$N"
+
+    # Move GRUB files to the right place.
+    mkdir -p $CDDIR/efi/boot
+    mcopy -i boot$N/isolinux/grub/efi.img ::efi/boot/bootx64.efi $CDDIR/efi/boot/bootx64.efi
+    mkdir -p $CDDIR/boot/grub
+    mv boot$N/isolinux/grub/* $CDDIR/boot/grub/
+    rmdir boot$N/isolinux/grub
+
+    # Create grub menu entries to match the isolinux ones
+    sed -i '/^menuentry/Q' $CDDIR/boot/grub/grub.cfg;
+    $BASEDIR/tools/boot/$DI_CODENAME/parse_isolinux \
+        boot$N/isolinux $CDDIR $BASEDIR/data/$DI_CODENAME/grub-theme.in "$DISKINFO_DISTRO" "$DEBIAN_KERNEL" "$DEBVERSION" \
+        >> $CDDIR/boot/grub/grub.cfg
+
+    # Stuff the EFI boot files into a FAT filesystem, making it as
+    # small as possible.  24KiB headroom seems to be enough;
+    # (x+31)/32*32 rounds up to multiple of 32.
+    # This is the same as in efi-image, but we need to redo it here in
+    # the case of a multi-arch amd64/i386 image
+
+    size=0
+    for file in $CDDIR/efi/boot/boot*.efi; do
+        size=$(($size + $(stat -c %s "$file")))
+    done
+
+    blocks=$((($size / 1024 + 55) / 32 * 32 ))
+
+    rm -f $CDDIR/boot/grub/efi.img
+    mkfs.msdos -C "$CDDIR/boot/grub/efi.img" $blocks >/dev/null
+    mmd -i "$CDDIR/boot/grub/efi.img" ::efi
+    mmd -i "$CDDIR/boot/grub/efi.img" ::efi/boot
+    mcopy -i "$CDDIR/boot/grub/efi.img" $CDDIR/efi/boot/boot*.efi \
+        "::efi/boot"
+
+    # Ugh - different code here depending on the version of xorriso we've got
+    if [ $XORRISO_VER -le 10202 ] ; then
+        # 1.2.2 shipping in Wheezy
+        echo "Using older EFI command line for xorriso $XORRISO_VER"
+        # Tell xorriso to create a secondary ElTorito boot record for the
+        # EFI bootloader
+        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-eltorito-alt-boot --efi-boot boot/grub/efi.img"
+        # Add the efi image as a FAT partition too, so our CD image will
+        # also boot on a USB key (like isohybrid, just implemented
+        # differently)
+        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-append_partition 2 0x01 $CDDIR/boot/grub/efi.img"
+
+    elif [ $XORRISO_VER -gt 10202 ] ; then
+        echo "Using newer EFI support in xorriso $XORRISO_VER"
+        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-eltorito-alt-boot -e boot/grub/efi.img -no-emul-boot"
+        add_mkisofs_opt $CDDIR/../$N.mkisofs_opts "-isohybrid-gpt-basdat -isohybrid-apm-hfsplus"
+    fi	
+else
+    echo "  No EFI boot code for $ARCH on CD$N"
+fi
+
 # th,th, thats all
+
diff --git a/debian-cd/tools/grab_md5 b/debian-cd/tools/grab_md5
--- a/debian-cd/tools/grab_md5
+++ b/debian-cd/tools/grab_md5
@@ -8,6 +8,8 @@
 # Parse Packages and Sources files out of a mirror and pre-process
 # them into a single list ready for mkisofs to check later
 
+set -e
+
 MIRROR=$1
 ARCHES="$2"
 CODENAME=$3
@@ -18,6 +20,13 @@ for ARCH in $ARCHES
 do
     LOCATIONS="$MIRROR/dists/$CODENAME/ $MIRROR/dists/$DI_CODENAME/"
     echo "Looking in $LOCATIONS"
+
+    for LOCATION in $LOCATIONS; do
+        if [ ! -d $LOCATION ]; then
+            echo "Error: $LOCATION is not a directory"
+            exit 1
+        fi
+    done
 
     case $ARCH in
         source)
